### ISSUE TITLE
datepicker not responsive and going out of viewport

### ISSUE THREAD

**Issue by flyingboy007** [indrimuska/angular-moment-picker#44]
I have 2 input field on the right side of the screen . So when I select the last input field which is to the end of the screen the datepicker is going out of bounds of the viewport.  How can I fix this? 

Here is the [pluncker](https://plnkr.co/edit/3FFqly?p=preview)

**Comment by indrimuska** [comment]
Hi @flyingboy007, in your plunker I just see two inputs in the left side of screen.

![image](https://cloud.githubusercontent.com/assets/1561134/16778897/5c1cb05e-4870-11e6-88c7-7803667d82ba.png)

**Comment by flyingboy007** [comment]
that works when the inputs are aligned horizintally..but if you make the screen bigger the input will all be laid out horizontally and the input which is to the end of the screen will go out of the screens visible width
(actually the calender goes out of screen and not the input )

![screenshot from 2016-07-13 02-10-55](https://cloud.githubusercontent.com/assets/6024513/16783021/eba65520-489f-11e6-9d8a-75c1c694f079.png)

**Comment by indrimuska** [comment]
Well, to avoid this there are many options:

- enlarge the input, at least at the width of the picker
- create a new property to align the picker to the right
- check whenever the screen size changes and align the picker correctly (using some css3 x-translation)

**Comment by indrimuska** [comment]
Right and Top align can be done by this piece of css:

```css
/* top */
.moment-picker.top .moment-picker-container { top: auto; bottom: 100%; margin-top: auto; margin-bottom: 4px; }
.moment-picker.top .moment-picker-container:before,
.moment-picker.top .moment-picker-container:after { border: 8px solid transparent; border-bottom: none; top: auto; bottom: -9px; }
.moment-picker.top .moment-picker-container:before { border-top-color: #f0f3f4; border-width: 9px; }
.moment-picker.top .moment-picker-container:after { border-top-color: #fff; margin-top: auto; margin-bottom: 1px; }

/* right */
.moment-picker.right .moment-picker-container { right: 0; margin-left: auto; margin-right: -.5em; }
.moment-picker.right .moment-picker-container:before,
.moment-picker.right .moment-picker-container:after { left: auto; right: 15px; }
.moment-picker.right .moment-picker-container:after { margin-left: auto; margin-right: 1px; }
```

Now, these are the options we can follow:

- check if the position of the picker fits outside the window and, otherwise, apply one of the styles above
- create two properties to let people choose which class to apply to align the picker on the left or on top
- both of the above
